### ISSUE TITLE
Couldn't find the nlp package in Android Studio

### ISSUE THREAD

**Issue by Yuhanlolo** [ocpsoft/prettytime#215] opened 2021-04-09 04:22 UTC
I added the dependency to my app build gradle. I see org.ocpsoft.prettytime imported in my external library, and packages such as Duration, LocaleAware, but not the nlp package. I'm using Android Studio 3.5.0. Did I miss anything?

**Comment by lincolnthree** [comment] 2021-04-09 17:01
> I added the dependency to my app build gradle.

Please post what you added. Need more info to assist. You do need to add *both* the PrettyTime core dep and also the NLP dep.

**Comment by Yuhanlolo** [comment] 2021-04-09 20:03
> > I added the dependency to my app build gradle.
> 
> Please post what you added. Need more info to assist. You do need to add _both_ the PrettyTime core dep and also the NLP dep.

I added: implementation 'org.ocpsoft.prettytime:prettytime:5.0.0.Final', not sure how to add the nlp dep, I just tried implementation 'org.ocpsoft.prettytime:prettytime-nlp:5.0.5.Final' but then my Android Studio freezed

**Comment by lincolnthree** [comment] 2021-04-12 14:34
@Yuhanlolo Ah. Not sure what to tell you about Android Studio freezing, but `5.0.0.Final` is the latest version of PrettyTime (and the NLP module)

**Comment by lincolnthree** [comment] 2021-04-12 14:35
https://mvnrepository.com/artifact/org.ocpsoft.prettytime/prettytime-nlp

**Comment by lincolnthree** [comment] 2021-04-24 19:54
Closing as cannot reproduce and no additional info provided.

**Closed by lincolnthree** 2021-04-24 19:54 UTC
